### ISSUE TITLE
Latest change breaks login: logincmd: unbound variable

### ISSUE THREAD

**Issue by 1Dimension1** [edgd1er/nordlynx-proxy#18]
Seems like logincmd is not set when using login + pass

/app/start_vpn.sh: line 149: logincmd: unbound variable
2022-12-23 10:25:30: ERROR: NORDVPN: cannot login: 
2022-12-23 10:25:30,502 INFO exited: start_vpn (exit status 1; not expected)

I'm still using this in my docker compose:
- NORDVPN_LOGIN=
- NORDVPN_PASS=

Do i need to use another method to login ?

**Comment by 1Dimension1** [comment]
Looks like its only set when using secrets and not environment variables.

`if [ -e /run/secrets/NORDVPN_CREDS ]; then`

My password is still in environment for now

**Comment by 1Dimension1** [comment]
Fixt it for now quick and dirty

`#Use secrets if present
if [ -e /run/secrets/NORDVPN_CREDS ]; then
  mapfile -t -n 2 vars </run/secrets/NORDVPN_CREDS
  if [[ ${#vars[*]} -eq 2 ]]; then
    NORDVPN_LOGIN=${vars[0]}
    NORDVPN_PASS=${vars[1]}
    logincmd="login --username ${vars[0]} --password ${vars[1]}"
  elif [[ ${#vars[*]} -eq 1 ]]; then
    log "WARNING: Only one line found, assuming token."
    NORDVPN_LOGIN=${vars[0]}
    NORDVPN_PASS=''
    logincmd="login -token ${vars[0]}"
  fi
else
    logincmd="login --username ${NORDVPN_LOGIN} --password "${NORDVPN_PASS}""
fi
`

**Comment by edgd1er** [comment]
Token is the preferred method as your credentials are not exposed. Login/password should be OK though .
I ll have to look at it.

**Comment by 1Dimension1** [comment]
I agree, will try and make a token :) Thanks for your work.
