### ISSUE TITLE
TOKEN environmant variable

### ISSUE THREAD

**Issue by thilo-adk** [edgd1er/nordlynx-proxy#24]
Hello,
it is planned to integrate the variable TOKEN?

"TOKEN - Used in place of USER and PASS for NordVPN account, can be generated in the web portal"

**Comment by edgd1er** [comment]
Hello,

I completed the readme as it was not clear how to use the token.
the `token`value can be defined in `NORDVPN_LOGIN` or with secrets.

https://github.com/edgd1er/nordlynx-proxy/blob/d75119bdf5a7297b668063985cc4c04f9b47d0f2/app/start_vpn.sh#L128-L133

https://github.com/edgd1er/nordlynx-proxy/blob/d75119bdf5a7297b668063985cc4c04f9b47d0f2/app/start_vpn.sh#L135-L148

**Comment by thilo-adk** [comment]
Perfect, it works.
Thanks.
