### ISSUE TITLE
Idea: Option to set Obfuscated servers

### ISSUE THREAD

**Issue by 1Dimension1** [edgd1er/nordlynx-proxy#29]
Maybe add environment variable to allow settings this option?

```
Obfuscated servers are specialized VPN servers that hide the fact that you’re using a VPN to reroute your traffic. They allow users to connect to a VPN even in heavily restrictive environments.

When you connect to a regular [VPN server](https://nordvpn.com/servers/), your ISP can’t see where you go online. But it knows that you’re using a VPN from the way your data looks. However, if you connect to an obfuscated server, it changes your data packets. Therefore, tools that are meant to block VPN traffic let it pass. No one notices you’re using a VPN, unless they inspect your data packets manually.

https://nordvpn.com/features/obfuscated-servers/
```

Type `nordvpn set obfuscate on` in the terminal window to enable the obfuscated servers, or type `nordvpn set obfuscate off` to disable obfuscated servers.

Obfuscated options only work on OpenVPN(TCP) and OpenVPN(UDP) protocols, so that means that Obfuscated servers are grayed out on the NordLynx or IKEv2 protocols.

**Comment by 1Dimension1** [comment]
Thanks alot, you're so quick. 
Will test it. BTW why analytics default = on ?

**Comment by edgd1er** [comment]
ANALYTICS was activate in all previous image, for the moment, if it can help Nordvpn to have a better understanding of the usage, why not, as long as disabling it is easy and documented.
Do you have the impression it shouldn't ?

**Comment by 1Dimension1** [comment]
I understand the point of helping NordVPN. Personally i think people are mostly using a VPN provider for privacy reasons and want as little analytics from anything. Those are just my 2 cents. 

For me it's ok how it is right now so that you can switch it on or off.
