### ISSUE TITLE
Using token but nordvpn asks for username

### ISSUE THREAD

**Issue by piemmepi** [edgd1er/nordlynx-proxy#31]
I am using a docker-compose.yml file basically the same as the example, uncommenting the username line and using my token there. However, I am getting this when trying to log in

What am I doing wrong?

[...]
pi-proxy-1  | 2023-07-01 16:29:26: ERROR: NORDVPN: cannot login: Incorrect Usage: flag provided but not defined: -username
pi-proxy-1  |
pi-proxy-1  |
pi-proxy-1  | nordvpn login - Logs you in
pi-proxy-1  |
pi-proxy-1  | Usage: nordvpn login command [command options] [arguments...]
pi-proxy-1  |
pi-proxy-1  | Commands:
pi-proxy-1  |      help, h  Shows a list of commands or help for one command
pi-proxy-1  |
pi-proxy-1  | Options:
pi-proxy-1  |    --nordaccount  (default: false)
pi-proxy-1  |    --callback     Usually used by the browser to finish Nord Account login flow. Also useful in headless setups. (default: false)
pi-proxy-1  |    --token        Use token login method. Does not support MFA. (default: false)
pi-proxy-1  |    --help, -h     show help
pi-proxy-1  |
pi-proxy-1  | flag provided but not defined: -username
pi-proxy-1  | 2023-07-01 16:29:26,443 WARN exited: start_vpn (exit status 1; not expected)
[...]

**Comment by piemmepi** [comment]
Ha - got it. Works by uncommenting username and commenting password and secret

**Comment by edgd1er** [comment]
* if using token, set NORDVPN_LOGIN with token value. (preferred method). NORDVPN_PASS should not be set.
* if using username and password, define both NORDVPN_LOGIN and NORDVPN_PASS 
I would suggest,though,  you use secrets so credentials are not in the env vars.

**Comment by edgd1er** [comment]
Please feel free to reopen if the issue still needs investigation
