### ISSUE TITLE
How to use 

### ISSUE THREAD

**Issue by parsahatami98** [edgd1er/nordlynx-proxy#33]
Can you explain more for new nordvpn login method --nordaccount
And what if i had logged in manually before running docker

**Comment by edgd1er** [comment]
Nordvpn client help is rather discrete.
```
nordvpn login --help
nordvpn login
Usage: nordvpn login [command options] [arguments...]

Options:
   --nordaccount  (default: false)
   --callback     Usually used by the browser to finish Nord Account login flow. Also useful in headless setups. (default: false)
   --token        Use token login method. Does not support MFA. (default: false)
   --help, -h     show help
```
this page is a bit more detailed: https://support.nordvpn.com/Connectivity/Linux/1325531132/Installing-and-using-NordVPN-on-Debian-Ubuntu-Raspberry-Pi-Elementary-OS-and-Linux-Mint.htm

As I understood, nordaccount is a way to login through a web browser. a graphic display and a direct connection to receive the callback function are required. Nothing workable with docker.

I suggest you create a token and define it in `NORDVPN_LOGIǸ , even better use docker secrets if possible (swarm or docker compose).
Token are created through that url: https://my.nordaccount.com/dashboard/nordvpn/manual-configuration/

I don't understand your last phrase. manually logged in another container ? on the website ? on another computer. please elaborate.

**Comment by parsahatami98** [comment]
Hello again
Yeah i know about the new policy of nordvpn 
I have logged in to my friend nord account via nordvpn login --callback 
I do not have access to get token because it's his account
But since i helped him a little bit in the payment i use it sometimes
So now in the linux debian i have logged in as you can see in the picture
![Screenshot_2023-07-24-23-50-18-551_com.server.auditor.ssh.client.jpg](https://github.com/edgd1er/nordlynx-proxy/assets/115446902/4a656689-2653-463c-8f01-ffac08a9dc81)

Now is it possible to use your code without nordvpn login requirement and skip the login part and use the nordvpn client to connect

**Comment by edgd1er** [comment]
> 

I'm afraid this project will be of no use as the login/password or token are required. Nordvpn client need it to authenticate yourself with nordvpn's servers. furthermore this project use docker.

a solution would be to install wireguard on the debian you are connected to, set technology to wireguard, connect to a server and then export the wireguard configuration, then use this project to run using wireguard and the configuration extracted.

Here's some inspiration: https://github.com/edgd1er/nordlynx-proxy/blob/cda3d3dbec8cf0d7a123e8c081b51445136cde33/app/start_vpn.sh#L85-L98

wireguard's keys are renewed by nordvpn, they need to be extracted regularly, not sure when though.

As this solution requires to install packages, large ones (300Mb approx), please check with your friend if that's ok, should the debian server be his.
