### ISSUE TITLE
env var NORDVPN_VERSION to 3.16.9 does not work

### ISSUE THREAD

**Issue by thilo-adk** [edgd1er/nordlynx-proxy#39]
Hi,

i set env var NORDVPN_VERSION to 3.16.9 but it does not work

> 0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 0 not upgraded.
Need to get 32.3 MB of archives.
After this operation, 9000 kB disk space will be freed.
Get:1 https://repo.nordvpn.com/deb/nordvpn/debian stable/main arm64 nordvpn arm64 3.16.9 [32.3 MB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 32.3 MB in 3s (10.6 MB/s)
dpkg: warning: downgrading nordvpn from 3.17.2 to 3.16.9
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 8990 files and directories currently installed.)
Preparing to unpack .../nordvpn_3.16.9_arm64.deb ...
[ERROR] Unknown environment `supervisord'
Unpacking nordvpn (3.16.9) over (3.17.2) ...
Setting up nordvpn (3.16.9) ...
2024-03-07 19:50:12: INFO: logall feature not available
2024-03-07 19:50:12,953 WARN exited: start_vpn (exit status 1; not expected)

**Comment by edgd1er** [comment]
I suspect the script stopped because of these two lines:
```
#exit if required vars are missing
[[ -z ${CONNECT:-''} ]] && exit 1
```
Could start your container with env var DEBUG=1 and check if the script stopped at this step ?
the problem is that var is set if not already set.
```
have you defined a country ? COUNTRY=<....>
there might be a situation when neither country and connect are defined, the script exits.
```

**Comment by raven4444** [comment]
I had a same issue, setting country resolved it.

**Comment by thilo-adk** [comment]
Hi.

very strange. The "COUNTRY=" option was no longer set, although I had set them. I have re-entered them and now it works.

regards.
